### PR TITLE
Add `azurerm_postgresql_configuration` resources to the module

### PR DESCRIPTION
**Pull request by Shr3ps**
This PR let us provide some custom configurations to the PostgreSQL Server.

### CODE REVIEW

**Comment by echuvyrov** [comment]
Hey @Shr3ps - thanks a ton for your contribution! Looks like there's a merge conflict now after we pulled in your tags change, ping me directly once resolved and I'll merge this PR.

Thanks a ton!

**Comment by Shr3ps** [comment]
Hi @echuvyrov I rebased the branch, seems good to merge 😺

**Comment by Shr3ps** [comment]
@echuvyrov Will you tag and publish a new version after this get merged ? thanks

**Comment by Shr3ps** [comment]
@echuvyrov Any news on this?

**Pull request merged**
